### ISSUE TITLE
Fix render Ubuntu 20

### ISSUE THREAD

**Issue by dblanm** [DanielTakeshi/gym-cloth#5]
Hi,

I tried to render in Ubuntu 20 but the render window does not update.
I created a fix in my fork commit by modifying `render/src/main.cpp`  [commit e810634ae4662f59973d04cbecd62eabe1aa9ae8](https://github.com/dblanm/gym-cloth/commit/e810634ae4662f59973d04cbecd62eabe1aa9ae8).

**Comment by DanielTakeshi** [comment]
Thanks @dblanm  ! 
We did this work on Ubuntu 16 and 18 systems (though usually 18). We haven't tested on 20, thanks for providing a solution.

Do you know if this will be backwards compatible?

**Comment by anonym-4989** [comment]
I have not checked in Ubuntu 16/18. 
I don't have any system with Ubuntu 16/18 so I cannot easily test it, but it would be nice if someone could!

**Comment by dblanm** [comment]
I haven't tested on Ubuntu 16/18.
I don't have any machine with 16/18, so it would be really nice if someone could test it!
